### ISSUE TITLE
Few improvements

### ISSUE THREAD

**Issue by rybbchao** [amosricky/CLI-fops#1]
Hi, this is the interviewer from Trend Micro. (@cheyilin)

Thanks for spending time for the test, this is a decent implementation in many ways like code structure, tests, vendor uses, management and basic CI automation.

Few improvement suggestions:

- [x] 1. Execute `fops` command **directly** instead of **interactive mode**.

- [x] 2. Define commands in their own file inside of the `cmd/` directory.

- [x] 3. Move helper functions to proper place (eg. `/pkg`), so each `/cmd/*.go` file is a single subcommand implementation.
- [x] 4. Add tests for each subcommand.

**Comment by rybbchao** [comment]
Thanks for the commits.

For 4, the helper functions (eg. **checkFile**) are still mixed with the implementation of command.

**Comment by amosricky** [comment]
I have move them to the proper place.
