### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rybbchao** [amosricky/CLI-fops#2]
These are some suggestions about error handling: (@CheyiLin)

- [x] 1. Avoid ignoring errors.

- [x] 2. Use `cobra.Command`'s hook `RunE` for better error handling.

**Comment by amosricky** [comment]
Use RunE to handle error instead of Run function -  a693d69.

**Comment by cheyilin** [comment]
Hi @amosricky 

Please note that don't close issue before you merge the changes to master, or you can mention that the fixes will be merged soon from other branches. Thanks!

**Comment by rybbchao** [comment]
Thanks for the commit.

For the suggestion 1, I've left a comment for [#a693d69](https://github.com/amosricky/CLI-fops/commit/a693d694bd16dd52675f0ebd56a16756c4bccb88). Please check if there are other **errors** missed.

**Comment by amosricky** [comment]
@CheyiLin  Got it.
@rybbchao Okay.
