### ISSUE TITLE
Unit test improvement

### ISSUE THREAD

**Issue by rybbchao** [amosricky/CLI-fops#5]
Seperate tests by tested functions into their own file whose name ends with **_test.go**. (@CheyiLin)

For example,

**cmd/checksum_test.go**:

```go
func TestChecksum(t *testing.T) {
    // test code
}
```

**Comment by amosricky** [comment]
okay, I have separated them.

**Comment by cheyilin** [comment]
Hi @amosricky,

Thanks for your work!
Please feel free to leave comments and close the issue if you think the code met the requirements.

**Comment by amosricky** [comment]
Got it.
